src/components/dataset/DatasetGrid.tsx
src/components/job/JobGrid.tsx
src/dataProvider/index.ts

* Add `search_query` filter to DatasetGrid & JobGrid components. Use filter value in `getList` method as API endpoint query param. Requires https://github.com/MobileTeleSystems/data-rentgen/pull/81 to be applied.
* Mark all table columns as non-sortable, as API does not support passing custom sorting field
* Replace list of actions above the table with custom one. Currently user may change column order and disable some columns if not need.
Screenshots:

[DOP-20135] Add search filter to dataset & job grids

---

src/App.tsx
src/components/job/JobShow.tsx
src/components/operation/OperationListFilters.tsx
src/components/operation/OperationListForRun.tsx
src/components/operation/OperationShow.tsx
src/components/operation/index.ts
src/components/run/RunList.tsx
src/components/run/RunListFilters.tsx
src/components/run/RunListForJob.tsx
src/components/run/RunShow.tsx
src/dataProvider/types.ts
src/i18n/en.ts

* Implemented `OperationListForRun` component. Added it to `RunShow` component, to render list of run's operations:
* Implemented `OperationShow` component
* Added `sortable=false` to `RunList*` components, to disallow react-admin to set custom sorting fields (API currently does not support that).
* Small fixes in `JobShow` component - fixed missing translations for `Runs` label, added `Divider`

[DOP-20144] Implement OperationListForRun & OperationShow

---

src/components/run/RunRaListForParentRun.tsx
src/components/run/RunRaShow.tsx
src/i18n/en.ts

Add `RunRaListForParentRun` component which renders list of child runs for specific parentRun. Added this component to "Child runs" tab of `RunRaShow` page.
Here is a screenshot with Airflow dag run page, listing its child Airflow task runs:

[DOP-21296] Add child runs list to RunRaShow page

---

src/components/lineage/LineageGraph.tsx
src/components/lineage/edges/BaseEdge.tsx
src/components/lineage/edges/IOEdge.tsx
src/components/lineage/edges/index.ts
src/components/lineage/utils/getGraphEdges.tsx
src/dataProvider/types.ts
src/utils/bytes.ts
src/utils/numbers.ts

Now API returns `num_rows`/`num_bytes`/`num_files` in the response, so we can show this stats on the edge.
What's changed:
* Added 2 edge types - `IOEdge` (complex label containing stats) and `BaseEdge` (just text label).
* Added formatting functions for bytes and numbers with rounding, to show value `10240 bytes` as `10KB`, and `12345` as `12K rows`, respectively.

[DOP-20148] Show amount of data on edge label

---

src/App.tsx
src/components/location/LocationRaEdit.tsx
src/components/location/index.ts
src/dataProvider/index.ts
src/i18n/en.ts

Implement `LocationRaEdit` component. It allows to set/reset `external_id` field of location, and sends a proper `PATCH` request to API. Other fields are currently read-only.

[DOP-20147] Implement location edit

---

src/components/lineage/nodes/dataset_node/DatasetNode.tsx
src/dataProvider/types.ts
src/i18n/en.ts

Previously when we encountered dataset with multiple schemas (input, output or both), we just ignored all of them. Now prefer latest output schema (as it mostly contains the entire set of columns), and fallback to latest input schema (may contain not all columns). If there are multiple schemas, show a note for user.

[DOP-22411] Prefer output schema of dataset

---

src/components/lineage/nodes/dataset_node/DatasetNode.tsx
src/components/lineage/utils/getGraphEdges.tsx
src/components/lineage/utils/getGraphNodes.ts
src/dataProvider/types.ts

API response for lineage API endpoint was changed from:
```javascript
{
"relations": [
{
"kind": "PARENT",
"from": {"kind": "JOB", "id": 123},
"to": {"kind": "RUN", "id": "00000000-0000-0000-0000-000000000000"},
},
{
"kind": "SYMLINK",
"from": {"kind": "DATASET", "id": 234},
"to": {"kind": "DATASET", "id": 999},
},
{
"kind": "INPUT",
"from": {"kind": "DATASET", "id": 234},
"to": {"kind": "OPERATION", "id": "11111111-1111-1111-1111-111111111111"},
},
{
"kind": "OUTPUT",
"from": {"kind": "OPERATION", "id": "11111111-1111-1111-1111-111111111111"},
"to": {"kind": "DATASET", "id": 234},
},
],
"nodes": [
{"kind": "DATASET", "id": 123, "name": "abc"},
{"kind": "JOB", "id": 234, "name": "cde"},
{
"kind": "RUN",
"id": "00000000-0000-0000-0000-000000000000",
"external_id": "def",
},
{
"kind": …
```

[DOP-23867] Adjust components to handle new lineage response schemas

---

src/components/base/DurationField.tsx
src/components/base/StatusField.tsx
src/components/dataset/DatasetRaList.tsx
src/components/dataset/DatasetRaRepr.tsx
src/components/dataset/DatasetRaShow.tsx
src/components/job/JobRaList.tsx
src/components/job/JobRaRepr.tsx
src/components/job/JobRaShow.tsx
src/components/job/JobRaTypeField.tsx
src/components/location/LocationRaEdit.tsx
src/components/location/LocationRaList.tsx
src/components/location/LocationRaNameWithLinkField.tsx
src/components/location/LocationRaRepr.tsx
src/components/location/LocationRaShow.tsx
src/components/location/LocationRaTypeWithIconField.tsx
src/components/operation/OperationRaLineage.tsx
src/components/operation/OperationRaListForRun.tsx
src/components/operation/OperationRaShow.tsx
src/components/run/RunRaExternalId.tsx
src/components/run/RunRaLineage.tsx
src/components/run/RunRaList.tsx
src/components/run/RunRaListForJob.tsx
src/components/run/RunRaListForParentRun.tsx
src/components/run/RunRaShow.tsx
src/dataProvider/types.ts
src/i18n/en.ts

API responses for list API were changed from:
```javascript
{
"kind": "OPERATION",
"id": ""11111111-1111-1111-1111-111111111111",
"name": "something",
}
```
to:
```javascript
{
"id": ""11111111-1111-1111-1111-111111111111",
"data": {
"id": ""11111111-1111-1111-1111-111111111111",
"name": "something",
}
}
```
To include computed fields to the response, like `statistics`. See https://github.com/MobileTeleSystems/data-rentgen/pull/158, https://github.com/MobileTeleSystems/data-rentgen/pull/159, https://github.com/MobileTeleSystems/data-rentgen/pull/160, https://github.com/MobileTeleSystems/data-rentgen/pull/161, https://github.com/MobileTeleSystems/data-rentgen/pull/162.
So I've adjusted all components to use `source="data.field"` instead of just `source="field"`.
ReactAdmin uses `source` to …

[DOP-22580] Adjust components to handle new detailed response schemas

---

src/components/base/IOStatisticsField.tsx
src/components/base/index.ts
src/components/job/JobRaShow.tsx
src/components/operation/OperationRaListForRun.tsx
src/components/operation/OperationRaShow.tsx
src/components/run/RunRaList.tsx
src/components/run/RunRaListForJob.tsx
src/components/run/RunRaListForParentRun.tsx
src/components/run/RunRaShow.tsx
src/i18n/en.ts
src/utils/bytes.ts
src/utils/numbers.ts

* Show statistics field in List and Show pages of runs and operations:
* If there are no operations within run (Airflow Task), show empty operations list in Operations tab. Same for inputs & outputs statistics and Lineage tab.
* If there are no inputs & outputs for operation, don't show Lineage tab at all. Unfortunately, can't do this for Run, as `FunctionField` messes up with tab name detection mechanism.
* Small change in number formatting function: instead of values `1.23`, `12.34`, `123.45` return `1.23`, `12.3`, `123` (total number of digits is always 3).
* Add missing `job.name` field to job Show page

[DOP-22580] Show run & operation statistics

---

src/components/dataset/DatasetRaList.tsx
src/components/job/JobRaList.tsx
src/components/lineage/LineageFilters.tsx
src/components/location/LocationRaList.tsx
src/components/operation/OperationRaListForRun.tsx
src/components/run/RunRaList.tsx
src/components/run/RunRaListForJob.tsx
src/components/run/RunRaListForParentRun.tsx

* Sync values of LineageFilters form with query params. If user opened page with URL like:
```
/#/datasets/873/show?filter=%7B%22since%22%3A%222024-02-10T00%3A00%22%2C%22depth%22%3A1%2C%22direction%22%3A%22UPSTREAM%22%2C%22granularity%22%3A%22JOB%22%7D
```
use values from `filter` field. When user clicks `Build lineage` button, filters are saved to URL, so it can be send to another user to show exactly the same lineage graph. Opening lineage tab without `filters` query part will lead to using default form values.
Also now lineage graph is build after page/Lineage tab is opened, just like other components, like RunList.

[DOP-22671] Store lineage filters in URL query params

---

src/components/lineage/nodes/dataset_node/DatasetNode.tsx
src/components/lineage/nodes/dataset_node/DatasetSchemaTable.tsx
src/components/lineage/nodes/dataset_node/utils/fieldMatchesText.ts
src/components/lineage/nodes/dataset_node/utils/flattenFields.ts
src/components/lineage/nodes/dataset_node/utils/index.ts
src/components/lineage/utils/pagination.ts
src/i18n/en.ts

Before:
After:
- Drop `description` field as it could be very long
- List of fields is paginated with 10 items per page by default:
User may change the page size, or to show all fields without the limit.
- Added a search text field which shows only fields with name or type matching user input:
Filter is applied on UI side, not backend.
- If node represents file path like `hdfs://cluster/app/warehouse/hive/somedb.db/sometable`, use title `.../somedb.db/sometable` instead of `.../sometable`, as database name is very important.

[DOP-22412] Improve Dataset node UX

---

src/components/lineage/converters/getGraphEdges.tsx
src/components/lineage/converters/getGraphNodes.ts
src/components/lineage/layout/buildLineageLayout.ts
src/components/lineage/nodes/dataset_node/DatasetNode.css
src/components/lineage/nodes/dataset_node/DatasetNode.tsx
src/components/lineage/nodes/dataset_node/DatasetSchemaTable.tsx
src/components/lineage/nodes/dataset_node/utils/flattenFields.ts
src/dataProvider/types.ts

Added edges for column lineage:
This is implemented by adding a Handler for each column in Dataset schema, and by connecting matching source+target column handlers with each other. Handlers are invisible.
Adjusted graph layout function to handle edges which are connected to virtual nodes.

[DOP-23920] Add column lineage edges

---

src/components/lineage/converters/getGraphNodes.ts
src/components/lineage/nodes/dataset_node/DatasetNode.tsx
src/components/lineage/nodes/job_node/JobNode.tsx

Title & subheader of DatasetNode and JobNode are now filled up in lineage layout helper functions instead of component render function. This allows to use proper node width and height for calculating graph layout

[DOP-23921] Use node width and height for calculating layout

---

src/components/lineage/LineageFilters.tsx
src/components/lineage/LineageView.tsx
src/components/lineage/converters/getGraphNodes.ts
src/components/lineage/nodes/dataset_node/DatasetNode.tsx
src/i18n/en.ts

Depends on adding new query param to lineage API in https://github.com/MobileTeleSystems/data-rentgen/pull/172.
With column lineage disabled (default):
With column lineage enabled:
DatasetNode height depends on number of fields in schema and if node has any column lineage. If column lineage is disabled or dataset columns are not related to any other dataset columns, then DatasetNode is compacted by default. User still may expand dataset schema, if required.

[DOP-23923] Add 'Column lineage' checkbox to LineageFilters

---

src/components/operation/OperationRaListFilters.tsx
src/components/run/RunRaList.tsx
src/components/run/RunRaListFilters.tsx
src/components/run/RunRaListForJob.tsx
src/components/run/RunRaListForParentRun.tsx

Depends on https://github.com/MobileTeleSystems/data-rentgen/pull/184.
Now `search_query` filter in `RunRaList` is optional, and there is no need to make additional check if user entered something here before sending request to backend.

[DOP-24369] Make search_query filter optional in RunRaList

---

src/components/lineage/converters/getGraphEdges.tsx

If total number of IO edges is higher 50+, disable animation to reduce browser CPU load while rendering each animation frame.

[DOP-24603] Disable animation for to many IOEdges

---

src/components/lineage/LineageGraph.tsx
src/components/lineage/edges/IOEdge.css
src/components/lineage/edges/IOEdge.tsx
src/components/lineage/nodes/dataset_node/DatasetSchemaTable.tsx
src/components/lineage/nodes/job_node/JobNode.css
src/components/lineage/nodes/job_node/JobNode.tsx
src/components/lineage/nodes/operation_node/OperationNode.tsx
src/components/lineage/nodes/operation_node/OperationNodeList.tsx
src/components/lineage/nodes/run_node/RunNode.tsx
src/components/lineage/nodes/run_node/RunNodeList.tsx
src/components/lineage/selection/LineageSelectionContext.tsx
src/components/lineage/selection/useLineageSelectionProvider.tsx
src/components/lineage/selection/utils/common.ts
src/components/lineage/selection/utils/edgeSelection.ts
src/components/lineage/selection/utils/handleSelection.ts
src/i18n/en.ts

Before clicking on any run or operation within JobNode selected the whole JobNode.
Now clicking on RunNode/OperationNode selects only this node and connected edges:
Double click selects connected nodes and edges recursively:
Implementation just the same as for DatasetNode + list of fields in dataset schema. So I've replaced everything related to `column` with more generic `handle` in selection helper functions.
Also previously selecting IO edge haven't increased label z-index:
Fixed:

[DOP-24601] Add support for selecting RunNode/OperationNode by click

---

src/components/lineage/converters/getGraphEdges.tsx
src/components/lineage/converters/getGraphNodes.ts
src/dataProvider/types.ts

Before - datasets connected via SYMLINK relation have separated column lineage (before SYMLINK and after SYMLINK):
After - added artificial field-field connections for each schema of both datasets, making column lineage less fractured:

[DOP-25532] Make artificial column lineage for SYMLINK relations

---

src/components/icons.tsx
src/components/job/JobIcon.tsx
src/components/job/JobType.tsx
src/components/location/LocationIcon.tsx
src/i18n/en.ts
src/i18n/ru.ts

* Add translation item for `HIVE_SESSION`.
* Ad now we have integrations which are both Job type and Dataset location (e.g. Hive, Oracle), I've combined logic of fetching icon by external system name into `IconByName` component.

[DOP-26447] Add Hive support

---

src/components/dataset/DatasetRaListForLocation.tsx
src/components/dataset/index.ts
src/components/job/JobRaListForLocation.tsx
src/components/job/index.ts
src/components/location/LocationRaShow.tsx
src/i18n/en.ts
src/i18n/ru.ts

Add Dataset and Jobs tabs for Location page.
On tabs we can see jobs and datasets which are relevant to current location.

[DOP-22571] add Datasets and Jobs tabs for Location page
